name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (Ensure compatibility with your project)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Step 4: Navigate to the correct directory and build the project
      - name: Build with Maven
        working-directory: SDA_Project
        run: mvn clean verify

      # Step 5: Run SonarQube analysis
      - name: Run SonarQube Scan
        working-directory: SDA_Project
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn sonar:sonar \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.organization=your_organization \
              -Dsonar.host.url=https://sonarcloud.io

