name: Build and Analyze with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: List directory contents for debugging
      - name: List root directory
        run: ls -la

      # Step 3: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 4: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      # Step 5: Navigate to the correct directory and build
      - name: Build with Maven
        run: |
          cd SDA_Project
          ls -la  # List contents for debugging
          mvn clean verify

      # Step 6: Run SonarQube analysis
      - name: Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd SDA_Project
          mvn sonar:sonar \
              -Dsonar.projectKey=your_project_key \
              -Dsonar.organization=your_organization \
              -Dsonar.host.url=https://sonarcloud.io
